#  GPT(Generative Pre-trained Transformer)

## 1. ChatGPT의 역사

![](https://wikidocs.net/images/page/184363/gpt0.PNG)

- BERT가 트랜스포머의 '인코더'로 설계된 모델이라면,
- GPT는 트랜스포머의 '디코더'로 설계된 모델.

- Open AI는 2019년에 GPT-1을 공개한 이후로,
- 2019년 GPT-2, 2020년 GPT-3, 2022년 ChatGPT(GPT 3.5), 2023년에는 GPT-4, 2024년에는 GPT-4o를 공개하며 GPT 시리즈를 발전시켜 왔습니다.



| &nbsp;       | GPT-1     | GPT-2 | GPT-3  | GPT-3.5 | GPT-4 Models |
|--------------|-----------|-------|--------|---------|--------------|
| 파라미터 개수      | 1억 1700만개 | 15억   | 1,750억 | ?       | 1조 8천억(추정)   |
| 디코더의 층       | 12        | 48    | 96     | ?       | ?            |
| 처리 가능한 토큰 개수 | 512       | 1024  | 2048   | ?       | 128,000      |
| 은닉층의 크기      | 768       | 1600  | 12288  | ?       | ?            |


## 2. 거대 언어 모델(Large Language Model)

- 언어 모델(Language Model)은 인공 지능 분야에서 컴퓨터가 사람의 언어를 이해하고 생성할 수 있도록 하는 기술입니다.

- 이 모델은 대규모의 텍스트 데이터를 통해, 이전 단어들로부터 다음 단어를 예측하는 방식으로 작동합니다.

  - 예를 들어, "아침에 일어나 창문을 열었더니"라는 문장이 주어지면, 언어 모델은 가장 그럴 듯한 다음 단어들을 나열하여 "바람이 상쾌하게 불어왔다"와 같은 이어지는 문장을 예측하는 모델입니다.

- 언어 모델의 대표적인 예로는 OpenAI의 GPT(Generative Pre-trained Transformer) 시리즈가 있습니다.

- 많은 입문자들이 착각하는 내용은 언어 모델과 GPT는 동격의 개념이 아니라는 것입니다.

- 기본적으로 언어 모델은 이전 단어들로부터 다음 단어를 예측하는 생성 모델이고, GPT는 수많은 언어 모델 중 하나입니다.
  - 예를 들어서 구글의 Gemini, 앤트로픽의 Claude, 네이버의 CLOVA X와 같은 모델들도 언어 모델 중 하나일 것입니다.
  
- 이 중 딥 러닝 언어 모델로서 **파라미터 개수가 충분히 큰 언어 모델**을 우리는 **거대 언어 모델(Large Language Model)**이라고 부릅니다.

## 3. GPT의 아키텍처

![](https://wikidocs.net/images/page/184363/gpt2.png)

- 트랜스포머: (인코더-디코더) 구조
- BERT : 인코더-디코더 아키텍처에서 인코더만 분리한 모델

- **GPT(디코더 Only)** : 기본적으로 트랜스포머 디코더로만 구성

  - GPT는 기본적으로 BERT와는 달리 '이전 단어'들로부터 '다음 단어'를 예측하는 모델 이기 때문에,

  - 다음 단어를 지속적으로 생성할 수 있어 기본적으로 '글쓰기'가 가능한 '생성 모델'입니다.

  - 트랜스포머 디코더 아키텍처를 가지며 다음 단어를 생성하는 이러한 구조는 현재 대부분의 거대 언어 모델이 채택하고 있는 구조이기도 합니다.



**[↓그림: GPT-2 아키텍처]**

![](https://wikidocs.net/images/page/184363/gpt3.PNG)

- 위의 GPT-2 아키텍처를 도식화한 그림은 트랜스포머 디코더 층이 이전에 배웠던 초기 트랜스포머 디코더 층과 크게 다르지 않음을 보여줍니다.

- 이전에 배웠던 트랜스포머에서의 디코더는 인코더가 같이 존재하는 아키텍처였기 때문에 인코더-디코더 어텐션이 존재했는데 여기서는 해당 부분이 제거되었습니다.

**[GPT-1, GPT-2, GPT-3 아키텍쳐 비교]**

![](https://wikidocs.net/images/page/184363/gpt.PNG)

- 사실 GPT-1, GPT-2, GPT-3는 아키텍처 상으로는 큰 차이를 보이지 않습니다.

1. GPT-1
  - 예컨대, GPT-1은 초기 트랜스포머 디코더에서 인코더-디코더 어텐션이 제거된 아키텍처이고,

1. GPT-2
  - GPT-1에서는 층 정규화(Layer Normalization)가 서브층(Sub layer) 다음에 위치한다면, GPT-2는 서브층(Sub layer)의 입력으로 이동되었습니다.

  - 그 외에는 초기화 방법이나, 단어 집합의 크기, 토큰 길이의 확장(GPT-1이 512였으나 GPT-2에서 1024로 증가) 정도의 차이를 가집니다.

1. GPT-3
  - 이는 GPT-2에서 GPT-3로 모델이 다시 한 번 변경되었을 때에도 마찬가지입니다. OpenAI는 GPT-3에서도 특별히 새로운 모델, 아키텍처, 알고리즘을 제안하지 않습니다.
  - 그저 모델이 거대 언어 모델(Large Language Model)이 되면서 새로운 능력들이 발현되기 시작했다는 점이 뚜렷하게 볼 수 있는 차이점입니다.

# GPT-2 를 이용한 문장 생성

In [1]:
# 한국어로 사전학습된 GPT-2 사용하여, 다음 문장 예측.
#  KoGPT-2

In [2]:
import numpy as np
import random
import tensorflow as tf
from transformers import AutoTokenizer # 특정모델에 알맞은 tokenizer 를 자동으로 불러오는 유틸리티 클래스
from transformers import TFGPT2LMHeadModel

In [3]:
model = TFGPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained('skt/kogpt2-base-v2')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json: 0.00B [00:00, ?B/s]

pytorch_model.bin:   0%|          | 0.00/513M [00:00<?, ?B/s]

TensorFlow and JAX classes are deprecated and will be removed in Transformers v5. We recommend migrating to PyTorch classes or pinning your version of Transformers.
Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['transformer.h.9.attn.masked_bias', 'lm_head.weight', 'transformer.h.5.attn.masked_bias', 'transformer.h.6.attn.masked_bias', 'transformer.h.7.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.11.attn.masked_bias', 'transformer.h.3.attn.masked_bias', 'transformer.h.2.attn.masked_bias', 'transformer.h.4.attn.masked_bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.8.attn.masked_bias', 'transformer.h.10.attn.masked_bias']
- This IS expected if you are initializing TFGPT2LMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFGPT

tokenizer.json: 0.00B [00:00, ?B/s]

In [4]:
sent = "근육이 커지기 위해서는"

In [5]:
input_ids = tokenizer.encode(sent)
input_ids = tf.convert_to_tensor([input_ids])

input_ids

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[33245, 10114, 12748, 11357]], dtype=int32)>

In [6]:
output = model.generate(input_ids,
               max_length=128,
               repetition_penalty=2.0,  # 텍스트 생성 같은 단어나 토큰이 과도하게 반복되는 것을 방지하기 위한 파라미터
               use_cache=True)

output

<tf.Tensor: shape=(1, 128), dtype=int32, numpy=
array([[33245, 10114, 12748, 11357, 23879, 39306,  9684,  7884, 10211,
        15177, 26421,   387, 17339,  7889,  9908, 15768,  6903, 15386,
         8146, 12923,  9228, 18651, 42600,  9564, 17764,  9033,  9199,
        14441,  7335,  8704, 12557, 32030,  9510, 18595,  9025, 10571,
        25741, 10599, 13229,  9508,  7965,  8425, 33102,  9122, 21240,
         9801, 32106, 13579, 12442, 13235, 19430,  8022, 12972,  9566,
        11178,  9554, 24873,  7198,  9391, 12486,  8711,  9346,  7071,
        36736,  9693, 12006,  9038, 10279, 36122,  9960,  8405, 10826,
        18988, 25998,  9292,  7671,  9465,  7489,  9277, 10137,  9677,
         9248,  9912, 12834, 11488, 13417,  7407,  8428,  8137,  9430,
        14222, 11356, 10061,  9885, 19265,  9377, 20305,  7991,  9178,
         9648,  9133, 10021, 10138, 30315, 21833,  9362,  9301,  9685,
        11584,  9447, 42129, 10124,  7532, 17932, 47123, 37544,  9355,
        15632,  9124, 10536, 

In [7]:
output_ids = output.numpy().tolist()[0]

print(output_ids)

[33245, 10114, 12748, 11357, 23879, 39306, 9684, 7884, 10211, 15177, 26421, 387, 17339, 7889, 9908, 15768, 6903, 15386, 8146, 12923, 9228, 18651, 42600, 9564, 17764, 9033, 9199, 14441, 7335, 8704, 12557, 32030, 9510, 18595, 9025, 10571, 25741, 10599, 13229, 9508, 7965, 8425, 33102, 9122, 21240, 9801, 32106, 13579, 12442, 13235, 19430, 8022, 12972, 9566, 11178, 9554, 24873, 7198, 9391, 12486, 8711, 9346, 7071, 36736, 9693, 12006, 9038, 10279, 36122, 9960, 8405, 10826, 18988, 25998, 9292, 7671, 9465, 7489, 9277, 10137, 9677, 9248, 9912, 12834, 11488, 13417, 7407, 8428, 8137, 9430, 14222, 11356, 10061, 9885, 19265, 9377, 20305, 7991, 9178, 9648, 9133, 10021, 10138, 30315, 21833, 9362, 9301, 9685, 11584, 9447, 42129, 10124, 7532, 17932, 47123, 37544, 9355, 15632, 9124, 10536, 13530, 12204, 9184, 36152, 9673, 9788, 9029, 11764]


In [8]:
print(tokenizer.decode(output_ids))

근육이 커지기 위해서는 무엇보다 규칙적인 생활습관이 중요하다.
특히, 아침식사는 단백질과 비타민이 풍부한 과일과 채소를 많이 섭취하는 것이 좋다.
또한 하루 30분 이상 충분한 수면을 취하는 것도 도움이 된다.
아침 식사를 거르지 않고 규칙적으로 운동을 하면 혈액순환에 도움을 줄 뿐만 아니라 신진대사를 촉진해 체내 노폐물을 배출하고 혈압을 낮춰준다.
운동은 하루에 10분 정도만 하는 게 좋으며 운동 후에는 반드시 스트레칭을 통해 근육량을 늘리고 유연성을 높여야 한다.
운동 후 바로 잠자리에 드는 것은 피해야 하며 특히 아침에 일어나면 몸이 피곤해지기 때문에 무리하게 움직이면 오히려 역효과가 날 수도 있다.
운동을


## Top5 뽑기

In [9]:
# "근육이 커지기 위해서는"  다음에 생설될 토큰 Top5

output = model(input_ids)
top5 = tf.math.top_k(output.logits[0, -1], k=5)

In [10]:
top5

TopKV2(values=<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([9.955053 , 9.470137 , 9.1222105, 9.1037855, 9.0559435],
      dtype=float32)>, indices=<tf.Tensor: shape=(5,), dtype=int32, numpy=array([23879, 12201, 11488, 14564, 20030], dtype=int32)>)

In [11]:
tokenizer.convert_ids_to_tokens(top5.indices.numpy())

['▁무엇보다', '▁우선', '▁반드시', '▁피부', '▁무엇보다도']

## Top5 로 문장 생성하기

In [12]:
sent = '근육이 커지기 위해서는'
input_ids = tokenizer.encode(sent)

while len(input_ids) < 50:
  output = model(np.array([input_ids]))
  # Top5 단어들 추출
  top5 = tf.math.top_k(output.logits[0, -1], k=5)
  # 위 Top5 단어들 중 랜덤으로 다음 단어 선택.
  token_id = random.choice(top5.indices.numpy())
  input_ids.append(token_id)

print(tokenizer.decode(input_ids))


근육이 커지기 위해서는 피부 타입, 각질, 주름 등을 꼼꼼히 살펴서 피부 상태를 확인해야 합니다.
또 평소에는 자외선 차단과 함께 자외선 차단지수 10점 만점으로 기초 화장품의 사용을 줄여주시는 것도 좋지만 평소에도 자외선이 강한 날에


In [13]:
# 근육이 커지기 위해서는 반드시 영양소를 보충할 필요하다. 영양소가 부족해 살이 찔 수 있다는 건 누구나 알지만 그걸 방치해두기 때문에 살이 찔 확률이 높아진다고 전문가들이 경고하는 것과 같은 원리다.
# 그렇게 살을 뺀 후엔 살이

In [14]:
# 근육이 커지기 위해서는 반드시 건강하고 튼튼한 식품을 선택하는 것이 중요하다"며, "최근의 영양소 파괴에 의해 체지방이 증가하고 지방세포의 생착률 역시 감소한 상태여서 영양소를 파괴한 음식을 피하는 것이 가장 효과적이며, 체지방이 많이



In [15]:
# 근육이 커지기 위해서는 무엇보다 면역력 제고에 도움이 돼 면역력을 높여줘야만 한다."고 조언한다. 면역력의 핵심은 '생명과 활력의 조화'이다.
# 이러면 자연스런 건강의 길도 열린다
# 건강한 몸을 유지하는 것이 가장 중요하다.
# 이

# GPT-2 를 이용한 챗봇

In [ ]:
import numpy as np
import random
import tensorflow as tf
from transformers import AutoTokenizer # 특정모델에 알맞은 tokenizer 를 자동으로 불러오는 유틸리티 클래스
from transformers import TFGPT2LMHeadModel

## KoGPT-2 의 모델과 토크나이저

In [16]:
model = TFGPT2LMHeadModel.from_pretrained('skt/kogpt2-base-v2', from_pt=True)
tokenizer = AutoTokenizer.from_pretrained('skt/kogpt2-base-v2',
                                          bos_token='</s>', eos_token='</s>', pad_token='<pad>')

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFGPT2LMHeadModel: ['transformer.h.9.attn.masked_bias', 'lm_head.weight', 'transformer.h.5.attn.masked_bias', 'transformer.h.6.attn.masked_bias', 'transformer.h.7.attn.masked_bias', 'transformer.h.1.attn.masked_bias', 'transformer.h.11.attn.masked_bias', 'transformer.h.3.attn.masked_bias', 'transformer.h.2.attn.masked_bias', 'transformer.h.4.attn.masked_bias', 'transformer.h.0.attn.masked_bias', 'transformer.h.8.attn.masked_bias', 'transformer.h.10.attn.masked_bias']
- This IS expected if you are initializing TFGPT2LMHeadModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFGPT2LMHeadModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassifica

In [17]:
print(tokenizer.bos_token_id)  # 1
print(tokenizer.eos_token_id)  # 1
print(tokenizer.pad_token_id)  # 3
print('-' * 10)
print(tokenizer.decode(1))
print(tokenizer.decode(2))
print(tokenizer.decode(3))
print(tokenizer.decode(4))


1
1
3
----------
</s>
<usr>
<pad>
<sys>


## 챗봇 데이터 로드

In [18]:
import pandas as pd
import tqdm
import urllib.request

In [19]:
urllib.request.urlretrieve("https://raw.githubusercontent.com/songys/Chatbot_data/master/ChatbotData.csv", filename="ChatBotData.csv")
train_data = pd.read_csv('ChatBotData.csv')
print('챗봇 데이터의 개수 :', len(train_data))


챗봇 데이터의 개수 : 11823


In [20]:
train_data

Q                         A  label
0                       12시 땡!                하루가 또 가네요.      0
1                  1지망 학교 떨어졌어                 위로해 드립니다.      0
2                 3박4일 놀러가고 싶다               여행은 언제나 좋죠.      0
3              3박4일 정도 놀러가고 싶다               여행은 언제나 좋죠.      0
4                      PPL 심하네                눈살이 찌푸려지죠.      0
...                        ...                       ...    ...
11818           훔쳐보는 것도 눈치 보임.        티가 나니까 눈치가 보이는 거죠!      2
11819           훔쳐보는 것도 눈치 보임.             훔쳐보는 거 티나나봐요.      2
11820              흑기사 해주는 짝남.                    설렜겠어요.      2
11821  힘든 연애 좋은 연애라는게 무슨 차이일까?  잘 헤어질 수 있는 사이 여부인 거 같아요.      2
11822               힘들어서 결혼할까봐        도피성 결혼은 하지 않길 바라요.      2

[11823 rows x 3 columns]

## 데이터 전처리

In [21]:
def get_chat_data():
  for question, answer in zip(train_data['Q'].to_list(), train_data['A'].to_list()):
    # question 은 User 메세지로 -> <usr> 토큰으로 시작
    # answer 는 system 메세지로 -> <sys> 토큰으로 시작
    sent = tokenizer.encode('<usr>' + question + '<sys>' + answer)
    yield [tokenizer.bos_token_id] + sent + [tokenizer.eos_token_id]


In [22]:
batch_size = 32
dataset = tf.data.Dataset.from_generator(get_chat_data, output_types=tf.int32)

# batch_size 만큼의 배치로 데이터 구성, 패딩토큰으로 패딩
dataset = dataset.padded_batch(batch_size=batch_size, padded_shapes=(None,), padding_values=tokenizer.pad_token_id)


In [23]:
for batch in dataset:
  print(batch)
  break

tf.Tensor(
[[    1     2  9349  7888   739  7318   376     4 12557  6824  9108  9028
   7098 25856     1     3     3     3     3     3     3     3     3     3
      3     3     3     3     3     3]
 [    1     2  9020  8263  7497 10192 11615  8210  8006     4 12422  8711
   9535  7483 12521     1     3     3     3     3     3     3     3     3
      3     3     3     3     3     3]
 [    1     2  9085  7597   395  8149 10624  7397 24224 13358  7182     4
  12079  8135 16899  9677  8234   389     1     3     3     3     3     3
      3     3     3     3     3     3]
 [    1     2  9085  7597   395  8149  9465 10624  7397 24224 13358  7182
      4 12079  8135 16899  9677  8234   389     1     3     3     3     3
      3     3     3     3     3     3]
 [    1     2  9943   422   418  9327  8702  7098     4  9847 16912 18328
   8671  7415  8263  8234   389     1     3     3     3     3     3     3
      3     3     3     3     3     3]
 [    1     2  9815   410 21249 10174  6824  8210  800

In [24]:
# 첫번째 배치의 첫번째 샘플
print(tokenizer.decode(batch[0]))

</s><usr> 12시 땡!<sys> 하루가 또 가네요.</s><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>


## 챗봇 학습하기

In [25]:
# 옵티마이저 결정
adam = tf.keras.optimizers.Adam(learning_rate=3e-5, epsilon=1e-08)

# 전체 데이터의 개수를 배치 크기로 나누면 하나의 에포크에서 실행되는 학습 횟수가 계산됨.
steps = len(train_data) // batch_size + 1

EPOCHS = 3

In [26]:
# tf.GradientTape
#   https://www.tensorflow.org/api_docs/python/tf/GradientTape
#   Record operations for automatic differentiation.  (자동미분)

#   텐서플로는 자동 미분(주어진 입력 변수에 대한 연산의 그래디언트(gradient)를 계산하는 것)을
#   위한 tf.GradientTape API를 제공합니다.
#   tf.GradientTape는 컨텍스트(context) 안에서 실행된 모든 연산을 테이프(tape)에 "기록"합니다.
#   그 다음 텐서플로는 후진 방식 자동 미분(reverse mode differentiation)을 사용해
#   테이프에 "기록된" 연산의 그래디언트를 계산합니다.

# tape.gradient(target, sources)를 통해,
#     target: 미분 대상 (예: 손실 함수)
#     sources: 미분할 변수들

# 참고: 그레디언트 및 자동 미분 소개, https://www.tensorflow.org/guide/autodiff?hl=ko


In [27]:
for epoch in range(EPOCHS):
  epoch_loss = 0

  for batch in tqdm.tqdm_notebook(dataset, total=steps):
    with tf.GradientTape() as tape:  # 실행된 모든 연산이 tape 에 기록
      result = model(batch, labels=batch)
      loss = result[0]
      batch_loss = tf.reduce_mean(loss)

    grads = tape.gradient(batch_loss, model.trainable_variables)  # 기울기 계산 (미분)
    adam.apply_gradients(zip(grads, model.trainable_variables))  # 기울기 적용
    epoch_loss += batch_loss / steps

  print('[Epoch: {:>4}] loss = {:>.9}'.format(epoch + 1, epoch_loss))

/tmp/ipython-input-1111581542.py:4: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for batch in tqdm.tqdm_notebook(dataset, total=steps):


  0%|          | 0/370 [00:00<?, ?it/s]

ResourceExhaustedError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} OOM when allocating tensor with shape[32,51200,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:BatchMatMulV2] name: 

## 챗봇 실행

In [ ]:
text = '오늘도 좋은 하루!'

sent = '<usr>' + text + '<sys>'  # 챗봇더러 <sys> 이후의 시퀀스를 생성하도록 함.

input_ids = [tokenizer.bos_token_id] + tokenizer.encode(sent)
input_ids = tf.convert_to_tensor([input_ids])
print('정수 인코딩 후 :', input_ids)
print('정수 인코딩을 재복원 :', tokenizer.decode(input_ids[0]))

# 정수 인코딩 후 : tf.Tensor([[    1     2 10070  7235 10586 12557   376     4]], shape=(1, 8), dtype=int32)
# 정수 인코딩을 재복원 : </s><usr> 오늘도 좋은 하루!<sys>

In [ ]:
output = model.generate(input_ids, max_length=50,
               early_stopping=True, eos_token_id=tokenizer.eos_token_id)

decoded_sentence = tokenizer.decode(output[0].numpy().tolist())
print(decoded_sentence)

# </s><usr> 오늘도 좋은 하루!<sys> 오늘도 좋은 하루네요.</s>

In [ ]:
print(decoded_sentence.split('<sys> ')[1].replace('</s>', ''))

# 오늘도 좋은 하루네요.

In [ ]:
output = model.generate(input_ids, max_length=50, do_sample=True, top_k=10)
decoded_sentence = tokenizer.decode(output[0].numpy().tolist())
print(decoded_sentence.split('<sys> ')[1].replace('</s>', ''))

In [ ]:
def return_answer_by_chatbot(user_text):
  sent = '<usr>' + user_text + '<sys>'
  input_ids = [tokenizer.bos_token_id] + tokenizer.encode(sent)
  input_ids = tf.convert_to_tensor([input_ids])
  output = model.generate(input_ids, max_length=50, do_sample=True, top_k=20)
  sentence = tokenizer.decode(output[0].numpy().tolist())
  chatbot_response = sentence.split('<sys> ')[1].replace('</s>', '')
  return chatbot_response

In [ ]:
sentences = [
    '안녕! 반가워~',
    '너는 누구야?',
    '너무 심심한데 나랑 놀자',
    '영화 해리포터 재밌어?',
    '너 딥 러닝 잘해?',
]

In [ ]:
for sentence in sentences:
  print(f'▶{sentence}')
  print(f'▷{return_answer_by_chatbot(sentence)}')
  print()