# 파이토치(PyTorch)

* 페이스북이 초기 루아(Lua) 언어로 개발된 토치(Torch)를 파이썬 버전으로 개발하여 2017년도에 공개
* 초기에 토치(Torch)는 넘파이(NumPy) 라이브러리처럼 과학 연산을 위한 라이브러리로 공개
* 이후 GPU를 이용한 텐서 조작 및 동적 신경망 구축이 가능하도록 딥러닝 프레임워크로 발전시킴
* 파이썬답게(pythonic) 만들어졌고, 유연하면서도 가속화된 계산 속도를 제공

# Tensorflow 대비 강점 (2025 현재)

* 새로운 논문도 PyTorch 구현이 많아짐
  * 최신 논문 코드 공개 시 PyTorch 구현이 압도적으로 많음
  * NeurIPS, CVPR, ACL 등 주요 학회에서 PyTorch 비율이 80% 이상
  * 새로운 아이디어를 구현·검증하는 속도가 빠름 → 연구 결과가 곧 PyTorch 생태계로 들어옴

* 산업 적용과 배포도 개선됨
  * 예전에는 TF → 산업, PyTorch → 연구로 나뉘었지만, 현재는 TorchServe, ONNX, PyTorch/XLA, TorchScript로 프로덕션 적용이 쉬워짐  (사실 배포, 모바일 부분은 여전히 TF가 PyTorch에 비해 강점임)
  * Meta, Microsoft, OpenAI 등 주요 빅테크가 PyTorch 기반
  * Hugging Face, OpenAI API 모델 등 최신 LLM/딥러닝 라이브러리도 PyTorch 우선 지원

* API 일관성과 간결함
  * TensorFlow는 tf.keras, tf.data, tf.function 등 하위 모듈 간 사용 방식이 달라서 학습 곡선이 큼
  * PyTorch는 Pythonic한 구조와 명확한 모듈 (torch, torch.nn, torch.utils.data)로 직관적
  * NumPy와 유사한 연산 방식 → 전환 장벽이 낮음

* 생태계 속도와 커뮤니티 대응
  * PyTorch는 새로운 기능 출시와 버그 픽스 속도가 빠름
  * 커뮤니티 포럼과 GitHub 이슈 응답이 활발
  * TensorFlow는 Google 내부 프로젝트 방향에 따라 기능이 갑자기 deprecated되거나 변경되는 경우가 잦음  

* **PyTorch vs TensorFlow (2025년)**

| 구분             | **PyTorch**                                        | **TensorFlow**                                        |
| -------------- | -------------------------------------------------- | ----------------------------------------------------- |
| **코드 실행 방식**   | Eager Execution 기본 (Python처럼 직관적)                  | Eager Execution 기본(TF 2.x) + 그래프 모드 혼합                |
| **디버깅 난이도**    | Python 디버거, `print()` 바로 사용 가능                     | 그래프 모드에서 디버깅 불편할 수 있음                                 |
| **API 일관성**    | 단순·직관적 (`torch`, `torch.nn`, `torch.utils.data`)   | 모듈 간 스타일 차이 있음 (`tf.keras`, `tf.data`, `tf.function`) |
| **연구 커뮤니티 비율** | 80% 이상 (NeurIPS, CVPR, ACL 등)                      | 연구 비중 적음                                              |
| **산업 채택**      | Meta, Microsoft, OpenAI, Hugging Face 등            | Google, DeepMind, 일부 기업                               |
| **모델 배포**      | TorchServe, ONNX, TorchScript, PyTorch/XLA         | TensorFlow Serving, TF Lite, TensorFlow\.js           |
| **생태계 속도**     | 빠른 기능 업데이트, 커뮤니티 피드백 활발                            | 안정성 중심, 하지만 변경/Deprecated 많음                          |
| **성능 최적화**     | PyTorch 2.x `torch.compile`로 JIT 최적화, GPU·TPU 지원   | XLA 최적화, TPU 성능 최적                                    |
| **모바일·경량화**    | Torch Mobile, ExecuTorch                           | TF Lite, Edge TPU                                     |
| **멀티플랫폼 지원**   | Linux, Windows, macOS, AWS Inferentia, Apple MPS 등 | 동일 + 브라우저(TF.js) 지원                                   |
| **학습 자료/예제**   | 최신 논문 구현 다수, GitHub 예제 풍부                          | 학습 자료 많음, 하지만 최신 연구 반영 속도 느림                          |
| **장점 요약**      | 연구·프로토타입 속도 최고, 직관적, 커뮤니티 표준                       | 배포·모바일·브라우저 친화적, Google 생태계와 통합                       |
| **단점 요약**      | 초창기 배포 약점은 개선됐지만 TF보다 모바일 쪽은 아직 덜성숙초창 |  API 복잡, 변경 빈번, 연구 커뮤니티 비중 낮음 |


# 파이토치의 구성요소

- `torch`: 메인 네임스페이스, 텐서 등의 다양한 수학 함수가 포함
- `torch.autograd`: 자동 미분 기능을 제공하는 라이브러리
- `torch.nn`: 신경망(neural network) 구축을 위한 데이터 구조나 레이어 등의 라이브러리
- `torch.multiprocessing`: 병럴처리 기능을 제공하는 라이브러리
- `torch.optim`: SGD(Stochastic Gradient Descent)를 중심으로 한 파라미터 최적화(optimizer) 알고리즘 제공
- `torch.utils`: 데이터 조작 등 유틸리티 기능 제공
- `torch.onnx`: ONNX(Open Neural Network Exchange), 서로 다른 프레임워크 간의 모델을 공유할 때 사용

# 🟦텐서(Tensors)

* 데이터 표현 (다차원 데이터)을 위한 기본 구조로 텐서(  Tensor)를 사용
* 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
* 넘파이(NumPy)의 ndarray와 유사
* GPU를 사용한 연산 가속 가능

## import

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

import torch
torch.__version__

'2.8.0+cu126'

## 텐서 초기화와 기본 속성

### tensor()
https://docs.pytorch.org/docs/stable/tensors.html

사용자가 입력한 값으로 텐서 초기화

In [ ]:
x = torch.tensor([1, 2, 3, 4, 5])  # 1차원 tensor
x

tensor([1, 2, 3, 4, 5])

In [ ]:
y = torch.tensor([[10.0, 10.1, 10.2], [20.0, 20.1, 20.2]])  # 2차원 tensor
y

tensor([[10.0000, 10.1000, 10.2000],
        [20.0000, 20.1000, 20.2000]])

In [ ]:
torch.tensor(100)  # 0차원 tensor (scalar)

tensor(100)

### type, shape, size(), ndim, dtype, numpy()

In [ ]:
type(x)

torch.Tensor

In [ ]:
x.shape

torch.Size([5])

In [ ]:
x.size()  # tensor의 크기, shape 와 동일

torch.Size([5])

In [ ]:
x.ndim

1

In [ ]:
x.dtype

torch.int64

In [ ]:
y.shape

torch.Size([2, 3])

In [ ]:
y.size()  # shape 와 동일

torch.Size([2, 3])

In [ ]:
y.numel() # 원소의 총 개수  number of element()

6

In [ ]:
# 각 차원별 접근 가능
print(y.size(0), y.size(1))
print(y.shape[0], y.shape[1])

2 3
2 3


In [ ]:
y.ndim

2

In [ ]:
y.dtype

torch.float32

In [ ]:
x = torch.tensor([1, 2.0])
print(x.dtype)
x

torch.float32


tensor([1., 2.])

In [ ]:
x.numpy()  # numpy 객체로 리턴

array([1., 2.], dtype=float32)

In [ ]:
x.tolist() # list 로 리턴

[1.0, 2.0]

### arange()
- np.arange() 와 비슷

In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x = torch.arange(12).reshape(3, 2, 2)
x

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

### empty()
- 초기화 되지 않은 텐서

In [ ]:
torch.empty(4, 2)  # 4 x 2 shape 의 초기화 되지 않은 Tensor 생성
# 값은 랜덤값  (garbage 값... )

tensor([[-4.5035e-08,  4.3471e-41],
        [-4.5035e-08,  4.3471e-41],
        [ 1.8524e+28,  2.1715e-18],
        [ 2.4283e-18,  1.7516e-43]])

### item() 스칼라값 추출
- 텐서에 값이 단 '하나' 만 존재하면 숫자값을 얻을수 있다.

In [ ]:
x

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [ ]:
# x.item()  # 에러 . element 가 복수개...

In [ ]:
x = torch.empty(1)
print(x)

tensor([-4.5036e-08])


In [ ]:
x.item()

-4.503579020820325e-08

### rand(), randn(), randint(), manual_seed()
무작위로 초기화된 텐서

In [ ]:
x = torch.rand(4, 2)  # [0, 1) 범위의 랜덤값으로 채워진 4 x 2 Tensor
x

tensor([[0.7872, 0.8604],
        [0.6614, 0.1178],
        [0.2097, 0.6055],
        [0.1269, 0.8989]])

In [ ]:
torch.manual_seed(42)

x = torch.rand(4, 2)
x

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009],
        [0.2566, 0.7936]])

In [ ]:
torch.randn(4, 2)  # 평균이 0, 표준편차가 1인 정규분포 난수 tensor 생성

tensor([[-1.1229, -0.1863],
        [ 2.2082, -0.6380],
        [ 0.4617,  0.2674],
        [ 0.5349,  0.8094]])

In [ ]:
torch.randint(0, 10, (3, 3))  # [0, 10) 사이의 정수랜덤값으로 3 x 3 Tensor 생성

tensor([[9, 3, 1],
        [9, 7, 9],
        [2, 0, 5]])

#### deterministic, non-deterministic 결정적, 비결정적
PyTorch 에서 **비결정적 연산(nondeterministic operations)** 이란, **같은 입력과 같은 조건을 주더라도 실행할 때마다 결과가 달라질 수 있는 연산**을 말합니다. 즉, 완전한 재현성이 보장되지 않는 연산입니다.

---

### 왜 비결정성이 생기는가?

비결정적 연산은 주로 **GPU 병렬 처리와 연관**이 있습니다. GPU에서는 성능 최적화를 위해 여러 쓰레드가 동시에 연산을 수행하는데, 연산 순서가 매번 다를 수 있습니다. 이때 **부동소수점 연산의 누적 오차**나 **atomic 연산의 순서 불확실성** 때문에 결과가 달라지게 됩니다.

---

### 대표적인 비결정적 연산 사례

PyTorch 공식 문서에 따르면, 아래와 같은 연산들이 비결정적일 수 있습니다:

1. **`torch.nn.Conv2d` (특정 cudnn 알고리즘 사용 시)**

   * cuDNN이 내부적으로 빠른 알고리즘을 사용하면서 결과 순서가 달라질 수 있음.

2. **Dropout 같은 난수 기반 연산**

   * 시드를 고정하지 않으면 실행할 때마다 다른 결과가 나옴.
   * 시드를 고정해도 GPU 비결정성 때문에 약간의 차이가 있을 수 있음.

3. **`torch.index_add_`, `scatter_` 같은 in-place 연산**

   * 여러 쓰레드가 같은 메모리 위치를 동시에 업데이트하면 순서에 따라 값이 달라짐.

4. **GPU에서의 backward 연산**

   * 예를 들어, 일부 RNN backward, atomicAdd 기반 gradient accumulation 등이 실행 순서에 따라 달라질 수 있음.

---

### 해결 방법

PyTorch는 **결정성 모드(deterministic mode)** 를 제공하여 가능한 경우 강제로 결정적 연산만 사용하도록 할 수 있습니다:

```python
import torch

# 결정성 강제
torch.use_deterministic_algorithms(True)

# CUDA 환경에서 비결정적 연산을 감지하도록 설정 (디버깅용)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
```

다만, 이 모드를 켜면:

* 일부 연산이 실행 불가(`RuntimeError`)가 될 수 있음
* 성능이 **크게 느려질 수 있음** (특히 GPU에서)

---

✅ 정리하면:

* PyTorch의 **비결정적 연산**은 **병렬 연산 순서 불확실성**이나 **난수 의존성** 때문에 결과가 매번 달라질 수 있는 연산을 말합니다.
* 완전한 재현성이 필요하다면 `torch.use_deterministic_algorithms(True)` 같은 설정으로 **결정성 강제**를 할 수 있지만, **성능 저하**를 감수해야 합니다.



In [ ]:
"""
※ 참고 램덤시드 주는 방법 정리

import torch
import random
import numpy as np

# Python 내장 random 모듈 시드
random.seed(42)

# NumPy 시드
np.random.seed(42)

# PyTorch 시드
torch.manual_seed(42)

# GPU 사용 시(단일 GPU)
torch.cuda.manual_seed(42)

# 멀티 GPU 환경일 경우
torch.cuda.manual_seed_all(42)

# 완전한 재현성 모드 설정
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False



실험을 여러번 했을 때 똑같은 결과를 보장하는 것을 '재현성(reproducibility)'  이라 한다

하지만 PyTorch의 완전한 재현성은
동일한 환경(OS, 라이브러리 버전, GPU 드라이버, PyTorch 버전 등)에서만 100% 보장됩니다.
CUDA 연산 중 일부는 여전히 비결정적(non-deterministic)일 수 있어,
필요하면 아래처럼 비결정적 연산 예외 처리도 추가할 수 있습니다.

torch.use_deterministic_algorithms(True)  <- ★주의: jupyter 환경에서 한번 설정하여 이후 셀에서도 계속 정용된다.
"""
None


In [ ]:
#  PyTorch 완전 재현성 보장용 시드 세팅 함수


import os
import random
import numpy as np
import torch

def set_seed(seed: int = 42):
    """
    PyTorch 완전 재현성 보장용 시드 세팅 함수

    Args:
        seed (int): 고정할 시드 값 (기본: 42)
    """
    # Python built-in random
    random.seed(seed)

    # 환경 변수
    os.environ["PYTHONHASHSEED"] = str(seed)

    # NumPy
    np.random.seed(seed)

    # PyTorch CPU
    torch.manual_seed(seed)

    # GPU (단일 및 멀티)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    # CuDNN 설정 - 완전 결정적 모드
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    # PyTorch 연산 결정적 모드 (1.8+)
    torch.use_deterministic_algorithms(True)

    print(f"[INFO] Random seed set to {seed} (full reproducibility mode)")

# 사용 예시
# set_seed(1234)

### ones, zeros, full

In [ ]:
x = torch.zeros(4, 2, dtype=torch.long)

In [ ]:
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

In [ ]:
x.dtype

torch.int64

In [ ]:
x = torch.ones(2, 4, dtype=torch.double)
x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

In [ ]:
x.dtype

torch.float64

In [ ]:
torch.full((2, 4), 55)

tensor([[55, 55, 55, 55],
        [55, 55, 55, 55]])

### rand_like(), randn_like(), zeros_like(), ones_like()
- 기존의 tensor 와 shape 이 같은 tensor 생성

In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
torch.randn_like(x)

tensor([[-0.0740, -0.3555,  0.3692],
        [-0.6200,  0.3825, -0.7136],
        [ 0.3640,  0.0138, -1.5816]])

In [ ]:
torch.rand_like(x)

tensor([[0.8572, 0.1165, 0.8596],
        [0.2636, 0.6855, 0.9696],
        [0.4295, 0.4961, 0.3849]])

In [ ]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

### new_ones(), new_zeros(), new_empty(), new_full()
- 기존 tensor 를 사용하여 만들수도 있다

In [ ]:
y = x.new_ones(5, 3, dtype=torch.int16)
y

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

In [ ]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x.new_empty(5, 3)

tensor([[3.0903e-27, 0.0000e+00, 6.1768e-27],
        [0.0000e+00, 1.5695e-43, 0.0000e+00],
        [6.7262e-44, 0.0000e+00, 3.1016e-27],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.6993e-04, 2.0773e+20, 1.9968e+20]])

## 데이터 타입(Data Type)
| Data type | dtype | CPU tensor | GPU tensor |
| ------ | ------ | ------ | ------ |
| 32-bit floating point | `torch.float32` or `torch.float` |`torch.FloatTensor` | `torch.cuda.FloatTensor` |
| 64-bit floating point | `torch.float64` or `torch.double` |`torch.DoubleTensor` | `torch.cuda.DoubleTensor` |
| 16-bit floating point | `torch.float16` or `torch.half` |`torch.HalfTensor` | `torch.cuda.HalfTensor` |
| 8-bit integer(unsinged) | `torch.uint8` |`torch.ByteTensor` | `torch.cuda.ByteTensor` |
| 8-bit integer(singed) | `torch.int8` |`torch.CharTensor` | `torch.cuda.CharTensor` |
| 16-bit integer(signed) | `torch.int16` or `torch.short` |`torch.ShortTensor` | `torch.cuda.ShortTensor` |
| 32-bit integer(signed) | `torch.int32` or `torch.int` |`torch.IntTensor` | `torch.cuda.IntTensor` |
| 64-bit integer(signed) | `torch.int64` or `torch.long` |`torch.LongTensor` | `torch.cuda.LongTensor` |

In [ ]:
x = torch.FloatTensor([1, 2, 3])
x

tensor([1., 2., 3.])

In [ ]:
x.dtype

torch.float32

In [ ]:
x = torch.IntTensor([1, 2, 3])
print(x)
print(x.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


### 타입 변환 short(), int(), long(), float(), double(), half()
- 기존의 tensor 의 dtype 변환한 tensor 생성

In [ ]:
x.short()

tensor([1, 2, 3], dtype=torch.int16)

In [ ]:
x.int()

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
x.long()  # dtype=torch.int64

tensor([1, 2, 3])

In [ ]:
x.float()  # dtype=torch.float32

tensor([1., 2., 3.])

In [ ]:
x.double()

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.half()

tensor([1., 2., 3.], dtype=torch.float16)

## to()  CPU, CUDA Tensors

- `.to` 메소드를 사용하여 텐서를 어떠한 장치(cpu, gpu)로도 옮길 수 있음

- `.to' 메소드는 Tensor나 nn.Module(모델)을 지정한 장치(device)나 자료형(dtype)으로 변환하는 역할을 합니다.
  - 즉, 연산이 이루어질 **위치(CPU, GPU)**와 **자료형(float32, float16 등)**를 바꾸는 기능

In [ ]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-1.2151])
-1.2151352167129517
torch.float32


In [ ]:
# torch.device("cpu")
# torch.device('cuda')

torch.cuda.is_available()

True

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
device

device(type='cuda')

In [ ]:
y = torch.ones_like(x, device=device)
y

tensor([1.], device='cuda:0')

In [ ]:
x = x.to(device)   # x 를 device로 옮김
x

tensor([-1.2151], device='cuda:0')

In [ ]:
z = x + y  # 계산결과도 동일하게 gpu 에 생성된다
print(z)


tensor([-0.2151], device='cuda:0')


In [ ]:
z.to('cpu', torch.double)

tensor([-0.2151], dtype=torch.float64)

## 다차원 텐서

In [ ]:
# 0D Tensor
#   하나의 스칼라 값만 갖고 있는 텐서
#   차원축(rank) 와 shape 가 없다.

In [ ]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [ ]:
# 1D Tensor (Vector)

In [ ]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [ ]:
# 2D Tensor (Matrix)
#  행 x 열 구조
#  샘플(sample) 과 특성(feature) 구조로 사용.

In [ ]:
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# 3D Tensor
#   차원축이 3개.
#   연속된 시퀀스 데이터, 시계열 데이터.
#   샘플 x 타임스텝 x 특성  의 구조.

In [ ]:
t3 = torch.tensor([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
    ],
    [
        [10, 20, 30, 40],
        [50, 60, 70, 80],
    ],
    [
        [100, 200, 300, 400],
        [500, 600, 700, 800],
    ],
])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 2, 4])
tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8]],

        [[ 10,  20,  30,  40],
         [ 50,  60,  70,  80]],

        [[100, 200, 300, 400],
         [500, 600, 700, 800]]])


## 텐서의 연산

In [ ]:
a = torch.tensor([-2.7, -1.2, 0.3, 1.2, 2.7])
print(a)

tensor([-2.7000, -1.2000,  0.3000,  1.2000,  2.7000])


In [ ]:
a * 2 - 1

tensor([-6.4000, -3.4000, -0.4000,  1.4000,  4.4000])

In [ ]:
# 각종 수학 함수
print(torch.abs(a), torch.ceil(a), torch.floor(a), torch.round(a))
print(a.abs(), a.ceil(), a.floor(), a.round())

tensor([2.7000, 1.2000, 0.3000, 1.2000, 2.7000]) tensor([-2., -1.,  1.,  2.,  3.]) tensor([-3., -2.,  0.,  1.,  2.]) tensor([-3., -1.,  0.,  1.,  3.])
tensor([2.7000, 1.2000, 0.3000, 1.2000, 2.7000]) tensor([-2., -1.,  1.,  2.,  3.]) tensor([-3., -2.,  0.,  1.,  2.]) tensor([-3., -1.,  0.,  1.,  3.])


### clamp

In [ ]:
print(a)
print(torch.clamp(a, -0.5, 0.5))
a.clamp(-0.5, 0.5)

tensor([-2.7000, -1.2000,  0.3000,  1.2000,  2.7000])
tensor([-0.5000, -0.5000,  0.3000,  0.5000,  0.5000])


tensor([-0.5000, -0.5000,  0.3000,  0.5000,  0.5000])

In [ ]:
# mean,std,sum,prod
print(a)
print(torch.mean(a), torch.sum(a), torch.std(a), torch.prod(a))
print(a.mean(), a.sum(), a.std(), a.prod())

tensor([-2.7000, -1.2000,  0.3000,  1.2000,  2.7000])
tensor(0.0600) tensor(0.3000) tensor(2.0936) tensor(3.1493)
tensor(0.0600) tensor(0.3000) tensor(2.0936) tensor(3.1493)


In [ ]:
# min, max, argmax, argmin
print(a)
print(torch.min(a), torch.max(a), torch.argmax(a), torch.argmin(a))
print(a.min(), a.max(), a.argmax(), a.argmin())

tensor([-2.7000, -1.2000,  0.3000,  1.2000,  2.7000])
tensor(-2.7000) tensor(2.7000) tensor(4) tensor(0)
tensor(-2.7000) tensor(2.7000) tensor(4) tensor(0)


In [ ]:
# unique : 중복제거된 tensor
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 2])))
print(torch.tensor([1, 2, 3, 1, 2, 2]).unique())

tensor([1, 2, 3])
tensor([1, 2, 3])


### dim=
- 특정 차원축을 따라서 연산

In [ ]:
torch.manual_seed(42)
x = torch.randint(0, 10, (4,2))
x

tensor([[2, 7],
        [6, 4],
        [6, 5],
        [0, 4]])

In [ ]:
x.sum(), x.max()

(tensor(34), tensor(7))

In [ ]:
x.sum(dim=0), x.sum(dim=1)

(tensor([14, 20]), tensor([ 9, 10, 11,  4]))

In [ ]:
x.max()

tensor(7)

In [ ]:
x.max(dim=0)

torch.return_types.max(
values=tensor([6, 7]),
indices=tensor([1, 0]))

In [ ]:
print(x.max(dim=0).values)
print(x.max(dim=0).indices)

tensor([6, 7])
tensor([1, 0])


### add, sub, mul, div
- +, -, *, /  연산자 사용 가능
- 기본적으로 원소끼리의 연산 (element-wise operation)
- 결과는 tensor 객체

In [ ]:
torch.manual_seed(42)
x = torch.randint(0, 10, (2, 2))
y = torch.randint(-10, 0, (2, 2))

print(x)
print(y)

tensor([[2, 7],
        [6, 4]])
tensor([[ -4,  -5],
        [-10,  -6]])


In [ ]:
print(x + y, x - y, x * y, x / y)
print(torch.add(x, y), torch.sub(x, y), torch.mul(x, y), torch.div(x, y))

tensor([[-2,  2],
        [-4, -2]]) tensor([[ 6, 12],
        [16, 10]]) tensor([[ -8, -35],
        [-60, -24]]) tensor([[-0.5000, -1.4000],
        [-0.6000, -0.6667]])
tensor([[-2,  2],
        [-4, -2]]) tensor([[ 6, 12],
        [16, 10]]) tensor([[ -8, -35],
        [-60, -24]]) tensor([[-0.5000, -1.4000],
        [-0.6000, -0.6667]])


### out=
- 결과 텐서를 제공

In [ ]:
result = torch.empty(2, 2)
print(result)


torch.add(x, y, out=result)   # x, y 연산결과를 result 텐서에 넣기
print(result)

tensor([[2.9017e-02, 0.0000e+00],
        [6.9897e+03, 0.0000e+00]])
tensor([[-2.,  2.],
        [-4., -2.]])


### in-place 방식
  - in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙음
  - `x.copy_(y), x.t_()`

In [ ]:
print(x)
print(y)

tensor([[2, 7],
        [6, 4]])
tensor([[ -4,  -5],
        [-10,  -6]])


In [ ]:
print(y.add(x))
print(y)  # y 값은 변화가 없다

tensor([[-2,  2],
        [-4, -2]])
tensor([[ -4,  -5],
        [-10,  -6]])


In [ ]:
y.add_(x)   # in-place 방식 add_()  => 원본 변경

tensor([[-2,  2],
        [-4, -2]])

In [ ]:
print(y)   # 변경되었다!

tensor([[-2,  2],
        [-4, -2]])


### matmul(), mm()
- `torch.mm`: 내적(dot product)
- matrix multiplication

In [ ]:
torch.matmul(x, y)

tensor([[-32, -10],
        [-28,   4]])

In [ ]:
torch.mm(x, y)

tensor([[-32, -10],
        [-28,   4]])

### svd  행렬 분해

-  특이값 분해(Singular Value Decomposition, SVD)
- 어떤 행렬을 세 개의 특수한 행렬의 곱으로 분해(decomposition) 함
- 활용용도
  - 차원 축소 (특히 PCA)
  - 선형 시스템 해법 (특히 과/부정방정식)
  - 데이터 압축
  - 노이즈 제거
  - 추천 시스템 (행렬 인수분해 기반 CF)

- **`svd()` 반환 값**

  * **U**: $m \times m$ 직교행렬
  * **S**: 특이값 벡터 ($\min(m, n)$ 길이)
  * **V**: $n \times n$ 직교행렬
(주의: 여기서 $V$는 $V^T$가 아니라, 수학 정의에서의 $V$ 그대로 반환)
  

In [ ]:
z = torch.matmul(x, y).float()
print(z)

tensor([[-32., -10.],
        [-28.,   4.]])


In [ ]:
torch.linalg.svd(z)

torch.return_types.linalg_svd(
U=tensor([[-0.7700, -0.6380],
        [-0.6380,  0.7700]]),
S=tensor([42.8158,  9.5292]),
Vh=tensor([[ 0.9927,  0.1202],
        [-0.1202,  0.9927]]))

### norm()
https://docs.pytorch.org/docs/stable/generated/torch.Tensor.norm.html

```python
torch.norm(input, p='fro', dim=None, keepdim=False, out=None, dtype=None)
```

- **텐서의 노름(norm)** 을 계산.
- 텐서를 하나의 "벡터" 또는 "행렬"로 보고 그 크기(길이)를 측정하는 연산

- 매개변수
  - p: 노름 차수 (기본값=2)
  - dim: 어떤 축에서 계산할지 (None이면 전체)
  - keepdim: 차원 유지 여부
  - dtype: 계산 시 데이터 타입 지정

In [ ]:
x = torch.tensor([3.0, 4.0])
print(x.norm())   # 기본은 p=2 → sqrt(3² + 4²) = 5.0

tensor(5.)


In [ ]:
print(x.norm(p=1))   #   |3| + |4| = 7.0
print(x.norm(p=2))
print(x.norm(p=3))   # L3 norm → (|3|³ + |4|³)^(1/3)

tensor(7.)
tensor(5.)
tensor(4.4979)


In [ ]:
x = torch.tensor([[1., 2.],
                  [3., 4.]])

x

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
print(x.norm())

tensor(5.4772)


In [ ]:
print(x.norm(p=1))

tensor(10.)


In [ ]:
print(x.norm(p=1, dim=0))

tensor([4., 6.])


In [ ]:
print(x.norm(p=1, dim=1))

tensor([3., 7.])


## 텐서의 조작 (manipulations)

### Indexing & slicing

In [ ]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x[0]

tensor([1., 2., 3., 4.])

In [ ]:
x[0, 0]

tensor(1.)

In [ ]:
x[1, 1]

tensor(6.)

In [ ]:
x[:, 0]

tensor([1., 5., 9.])

In [ ]:
x[..., 0]

tensor([1., 5., 9.])

In [ ]:
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

### `view`:
- 텐서의 크기(size)나 모양(shape)을 변경
  - 변경된 view 리턴
  - data 는 원본과 동일

- 기본적으로 변경 전과 후에 텐서 안의 원소 개수가 유지되어야 함
- -1로 설정되면 계산을 통해 해당 크기값을 유추
- reshape() 와 동작이 비슷.

In [ ]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
x.view(2, 2, 3)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [ ]:
x.reshape(2, 2, 3)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [ ]:
x.view(12)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x.view(-1)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x.view(3, -1)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

### `squeeze`: 차원을 축소(제거)
- 크기가 1 인 차원 제거

In [ ]:
x = torch.rand(1, 3, 3)
print(x)
print(x.shape)

tensor([[[0.9408, 0.1332, 0.9346],
         [0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854]]])
torch.Size([1, 3, 3])


In [ ]:
x.squeeze()  # (1, 3, 3) => (3, 3)

tensor([[0.9408, 0.1332, 0.9346],
        [0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854]])

In [ ]:
x.squeeze().shape

torch.Size([3, 3])

### `unsqueeze` : 차원을 증가(생성)

In [ ]:
x = torch.rand(3, 3)
print(x)
x.shape

tensor([[0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969],
        [0.8317, 0.1053, 0.2695]])


torch.Size([3, 3])

In [ ]:
y = x.unsqueeze(dim=0)   # 0번 차원축 추가 (3, 3) -> (1, 3, 3)
print(y.shape)
y

torch.Size([1, 3, 3])


tensor([[[0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969],
         [0.8317, 0.1053, 0.2695]]])

In [ ]:
y = x.unsqueeze(dim=2)   # 0번 차원축 추가 (3, 3) -> (3, 3, 1)
print(y.shape)
y

torch.Size([3, 3, 1])


tensor([[[0.5739],
         [0.2666],
         [0.6274]],

        [[0.2696],
         [0.4414],
         [0.2969]],

        [[0.8317],
         [0.1053],
         [0.2695]]])

### permute(dims) : 차원순서 재배치

- PyTorch 텐서의 차원 순서를 재배치하는 함수.
원래 데이터의 값은 그대로 두고, 차원 순서만 변경

    - dims: 원하는 차원 순서를 나타내는 튜플 또는 리스트

    - 반환: 새로운 차원 순서를 가진 view (메모리 복사 없이 차원 순서만 변경)

    - 원본 텐서는 변경되지 않음 (필요하면 .clone()으로 복사 가능)


- PyTorch는 이미지 데이터를 다룰때 채널 우선 형식 (C, H, W)을 사용하지만,
PIL 이미지나 NumPy 배열은 채널 마지막 형식 (H, W, C)을 가집니다.

  - 예를 들어, (H=224, W=224, C=3) → (C=3, H=224, W=224) 로 바꾸려면:
  - tensor.permute(2, 0, 1)  # C가 마지막(2) → 앞으로, H=0, W=1

In [ ]:
img = torch.randn(2, 3, 4)   # (Height, Width, Channel)
img.shape

torch.Size([2, 3, 4])

In [ ]:
img2 = img.permute(2, 0, 1)  # (H, W, C) -> (C, H, W)
img2.shape

torch.Size([4, 2, 3])

### `stack`: 텐서간 결합

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

x, y, z

(tensor([1., 4.]), tensor([2., 5.]), tensor([3., 6.]))

In [ ]:
torch.stack([x, y, z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

### `cat`: 텐서를 결합하는 메소드(concatenate)

- 넘파이의 `stack`과 유사하지만, 쌓을 `dim`이 존재해야함
- 해당 차원을 늘려준 후 결합


In [ ]:
x = torch.randn(1, 3, 3)
y = torch.randn(1, 3, 3)

x, y

(tensor([[[-0.5687,  1.2580, -1.5890],
          [-1.1208,  0.8423,  0.1744],
          [-2.1256,  0.9629,  0.7596]]]),
 tensor([[[ 0.7343, -0.6708,  2.7421],
          [ 0.5568, -0.8123,  1.1964],
          [ 0.8613, -1.3682, -0.7740]]]))

In [ ]:
torch.cat((x, y))   # dim=0   기본값   (1, 3, 3) + (1, 3, 3) => (2, 3, 3)

tensor([[[-0.5687,  1.2580, -1.5890],
         [-1.1208,  0.8423,  0.1744],
         [-2.1256,  0.9629,  0.7596]],

        [[ 0.7343, -0.6708,  2.7421],
         [ 0.5568, -0.8123,  1.1964],
         [ 0.8613, -1.3682, -0.7740]]])

In [ ]:
torch.cat((x, y), dim=0)

tensor([[[-0.5687,  1.2580, -1.5890],
         [-1.1208,  0.8423,  0.1744],
         [-2.1256,  0.9629,  0.7596]],

        [[ 0.7343, -0.6708,  2.7421],
         [ 0.5568, -0.8123,  1.1964],
         [ 0.8613, -1.3682, -0.7740]]])

In [ ]:
torch.cat((x, y), dim=1)  # (1,3,3) + (1,3,3) => (1, 6, 3)

tensor([[[-0.5687,  1.2580, -1.5890],
         [-1.1208,  0.8423,  0.1744],
         [-2.1256,  0.9629,  0.7596],
         [ 0.7343, -0.6708,  2.7421],
         [ 0.5568, -0.8123,  1.1964],
         [ 0.8613, -1.3682, -0.7740]]])

### `chunk` 나누기 (개수)
- 텐서를 여러 개로 나눌 때 사용 (몇 개로 나눌 것인가?)

https://docs.pytorch.org/docs/stable/generated/torch.chunk.html

```python
torch.chunk(input: Tensor, chunks: int, dim: int = 0) → Tuple[Tensor, ...]
```

In [ ]:
x = torch.arange(1, 19).reshape(3, 6)
x

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]])

In [ ]:
t1, t2, t3 = torch.chunk(x, chunks=3, dim=1)

In [ ]:
# (3, 6) => (3, 2), (3, 2), (3, 2)

In [ ]:
print(t1)
print(t2)
print(t3)

tensor([[ 1,  2],
        [ 7,  8],
        [13, 14]])
tensor([[ 3,  4],
        [ 9, 10],
        [15, 16]])
tensor([[ 5,  6],
        [11, 12],
        [17, 18]])


In [ ]:
t1, t2, t3 = torch.chunk(x, chunks=3, dim=0)

# (3,6) => (1,6) (1,6) (1,6) 3개로 쪼개진다

print(t1)
print(t2)
print(t3)

tensor([[1, 2, 3, 4, 5, 6]])
tensor([[ 7,  8,  9, 10, 11, 12]])
tensor([[13, 14, 15, 16, 17, 18]])


In [ ]:
torch.chunk(x, chunks=2, dim=0)  # (3,6) => (2,6) (1,6)

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12]]),
 tensor([[13, 14, 15, 16, 17, 18]]))

In [ ]:
torch.chunk(x, chunks=4, dim=0)   # (3,6) => (1,6) (1,6) (1,6)

(tensor([[1, 2, 3, 4, 5, 6]]),
 tensor([[ 7,  8,  9, 10, 11, 12]]),
 tensor([[13, 14, 15, 16, 17, 18]]))

### `split`: 나누기 (크기단위)
- `chunk`와 동일한 기능이지만 나누는 방식이 다름 (텐서의 크기는 몇인가?)

https://docs.pytorch.org/docs/stable/generated/torch.split.html

```python
torch.split(tensor, split_size_or_sections, dim=0) -> Tuple[Tensor, ...]
```


In [ ]:
x

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]])

In [ ]:
t1, t2 = torch.split(x, split_size_or_sections=3, dim=1)

# (3,6) -> (3, 3), (3, 3)  dim=1 의 크기가 3으로 쪼갬.

print(t1)
print(t2)

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]])
tensor([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18]])


### torch ↔ numpy
- Torch Tensor(텐서)를 NumPy array(배열)로 변환 가능
  - `numpy()`
  - `from_numpy()`
- Tensor가 CPU상에 있다면 NumPy 배열은 메모리 공간을 공유하므로 하나가 변하면, 다른 하나도 변함

In [ ]:
x

tensor([[11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22],
        [23, 24, 25, 26, 27, 28]])

In [ ]:
arr = x.numpy()
arr

array([[11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22],
       [23, 24, 25, 26, 27, 28]])

In [ ]:
x.add_(10)
print(x)

tensor([[21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32],
        [33, 34, 35, 36, 37, 38]])


In [ ]:
# Tensor 가 CPU 상에 있다면 Numpy 배열과 동일한 메모리 공간을 공유.
# 한쪽이 변하면 다른쪽도 변함.

arr

array([[21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38]])

In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x = torch.from_numpy(arr)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.add(arr, 10, out=arr)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
print(arr)
print(x) # tensor 도 변경되어 있다.

[10 11 12 13 14 15 16 17 18 19]
tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])


In [ ]:
x.tolist()

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

# 🟦Autograd(자동미분)

- `torch.autograd` 패키지는 Tensor의 모든 연산에 대해 **자동 미분** 제공
  - '기울기' 를 주어 학습이 이루어지게 함
- 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파(back propagation)가 정의된다는 뜻
- `backprop`를 위해 미분값을 자동으로 계산

## requires_grad= 속성
`requires_grad` 속성을 `True`로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

In [ ]:
torch.manual_seed(42)
x = torch.randn(3, 3)
print(x)
print(x.requires_grad)  # 기본값 False

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863],
        [ 2.2082, -0.6380,  0.4617]])
False


In [ ]:
x = x * 3
print(x)

tensor([[ 1.0101,  0.3864,  0.7034],
        [ 0.6910, -3.3686, -0.5590],
        [ 6.6246, -1.9140,  1.3850]])


In [ ]:
x.requires_grad = True
# x.requires_grad_(True)  # 이렇게 해도 된다 in-place 동작

In [ ]:
x.requires_grad

True

In [ ]:
x.grad_fn  # 미분값을 계산한 함수에 대한 정보.  현재 None 이다.

In [ ]:
# 다음의 연산을 x 에 대해 수행
y = (x * x).sum()
y

# tensor(63.2684, grad_fn=<SumBackward0>)  <- grad_fn=  이전 연산을 기록하고 있다

tensor(63.2684, grad_fn=<SumBackward0>)

In [ ]:
y.grad_fn  # 어떤 연산에 대해 back propagation 을 해야 하는지 기록하는게 grad_fn

## 기울기 (Gradient)

In [ ]:
x = torch.ones(3, 3, requires_grad=True)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [ ]:
y = x + 5  # x 에 +5 연산한 결과 y
print(y)  # grad_fn=<AddBackward0>  x로부터 덧셈한 결과라는 기록.

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]], grad_fn=<AddBackward0>)


In [ ]:
# 위 y 값에 또 연산을 수행해보자
z = y * y   # 연산
out = z.mean()  # 또 연산

print(z)  # grad_fn=<MulBackward0>
print(out) # grad_fn=<MeanBackward0>

tensor([[36., 36., 36.],
        [36., 36., 36.],
        [36., 36., 36.]], grad_fn=<MulBackward0>)
tensor(36., grad_fn=<MeanBackward0>)


### .backward()  와 .grad속성
계산이 완료된 후, `.backward()`를 호출하면 자동으로 역전파 계산이 가능하고, `.grad` 속성에 누적됨

In [ ]:
x.grad  # .grad : 미분값, 기울기

# 지금은 계산된게 없다.
# backward() 후에 계산된 것을 보게 될 거다!

In [ ]:
out.backward()  # 역전파 계산!  알아서 미분을 수행해 준다.

### .grad
`grad`: data가 거쳐온 layer에 대한 미분값 저장

In [ ]:
print(x)
print(x.grad)  # backward() 한 결과로 x 의 미분ㄱ밧이 자동계산되었다.

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])


### .data 속성
- torch.Tensor 객체에서 autograd(자동 미분) 관련 정보 없이 순수 값만 담은 텐서를 반환.

- 반환된 텐서는 원본 텐서와 메모리를 공유합니다.
→ 따라서 .data를 통해 값을 변경하면 원본에도 영향을 받음

- 주의: autograd 그래프를 무시합니다.
→ .data를 사용해 값을 바꾸면, PyTorch의 미분 기록(그래프)에 반영되지 않아서 그래디언트 계산이 꼬일 수 있음.

- PyTorch 개발자 문서에서도 .data를 권장하지 않음:

  - Instead of using .data, use with torch.no_grad(): or tensor.detach() for safe operations.

In [ ]:
torch.manual_seed(42)
x = torch.randn(3, requires_grad=True)
x

tensor([0.3367, 0.1288, 0.2345], requires_grad=True)

In [ ]:
x.data

tensor([0.3367, 0.1288, 0.2345])

In [ ]:
y = x * 2

while y.data.norm() < 1000:
  y = y * 2

print(y)

tensor([1379.0837,  527.6033,  960.3578], grad_fn=<MulBackward0>)


In [ ]:
x.grad

In [ ]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

y.backward(v)  # v 기준으로 backward 가 이루어진다.

x.grad  # x 의 기울기가 계산이 되었다!!!

tensor([4.0960e+02, 4.0960e+03, 4.0960e-01])

### with torch.no_grad()

`with torch.no_grad()`를 사용하여 기울기의 업데이트를 하지 않음

기록을 추적하는 것을 방지하기 위해 코드 블럭을 `with torch.no_grad()`로 감싸면 기울기 계산은 필요없지만, `requires_grad=True`로 설정되어 학습 가능한 매개변수를 갖는 모델을 **평가(evaluate)**할 때 유용

In [ ]:
x.requires_grad

True

In [ ]:
(x ** 2).requires_grad

True

In [ ]:
with torch.no_grad():   # 기울기 계산 안함
  print((x ** 2).requires_grad)

False


### .detach()
`detach()`: 내용물(content)은 같지만 `require_grad`가 다른 새로운 Tensor를 가져올 때

In [ ]:
x.requires_grad

True

In [ ]:
w = x.detach()    # x 에 detach 된 w 는 더이상 gradient 계산 안한다.
w.requires_grad  # False

False

In [ ]:
print(x)
print(w)

tensor([0.3367, 0.1288, 0.2345], requires_grad=True)
tensor([0.3367, 0.1288, 0.2345])


In [ ]:
x.eq(w)  # 두 tensor 는 같은가?  element-wise(원소별) 동등 비교 연산을 수행하는 함수
         # '동일 객체' 여부를 묻는 함수가 아니다.

tensor([True, True, True])

In [ ]:
x.eq(w).all()

tensor(True)